/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hafizh
 */
public class Main extends javax.swing.JFrame {
     private DefaultTableModel dtm;
     private int selectedID = -1;
     private ArrayList<Buku> listBuku;
     private ArrayList<Author> listAuthor;
     
     dbConnection conn = new dbConnection();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        pan_buku.setVisible(false);
        pan_author.setVisible(true);
        
        listBuku = new ArrayList<>();
        listAuthor = new ArrayList<>();
        
        tbl_author.setModel(conn.readTableAuthor());
        tbl_buku.setModel(conn.readTableBuku());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_author = new javax.swing.JPanel();
        btn_add_auth = new javax.swing.JButton();
        btn_buku_auth = new javax.swing.JButton();
        btn_author_auth = new javax.swing.JButton();
        pan_author_table = new javax.swing.JScrollPane();
        tbl_author = new javax.swing.JTable();
        pan_buku = new javax.swing.JPanel();
        btn_add_buku = new javax.swing.JButton();
        btn_buku_buku = new javax.swing.JButton();
        btn_author_buku = new javax.swing.JButton();
        pan_buku_table = new javax.swing.JScrollPane();
        tbl_buku = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_add_auth.setText("Add");
        btn_add_auth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_authMouseClicked(evt);
            }
        });

        btn_buku_auth.setText("Buku");
        btn_buku_auth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buku_authMouseClicked(evt);
            }
        });

        btn_author_auth.setText("Author");
        btn_author_auth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_author_authMouseClicked(evt);
            }
        });

        tbl_author.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nama", "jumlah buku"
            }
        ));
        pan_author_table.setViewportView(tbl_author);

        javax.swing.GroupLayout pan_authorLayout = new javax.swing.GroupLayout(pan_author);
        pan_author.setLayout(pan_authorLayout);
        pan_authorLayout.setHorizontalGroup(
            pan_authorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_authorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pan_authorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_author_auth)
                    .addComponent(btn_buku_auth))
                .addGap(181, 181, 181)
                .addComponent(btn_add_auth)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(pan_authorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_authorLayout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(pan_author_table, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        pan_authorLayout.setVerticalGroup(
            pan_authorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_authorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pan_authorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buku_auth)
                    .addComponent(btn_add_auth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_author_auth)
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(pan_authorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_authorLayout.createSequentialGroup()
                    .addContainerGap(111, Short.MAX_VALUE)
                    .addComponent(pan_author_table, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        btn_add_buku.setText("Add");
        btn_add_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_bukuMouseClicked(evt);
            }
        });

        btn_buku_buku.setText("Buku");
        btn_buku_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buku_bukuMouseClicked(evt);
            }
        });

        btn_author_buku.setText("Author");
        btn_author_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_author_bukuMouseClicked(evt);
            }
        });

        tbl_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "penerbit", "author", "desc"
            }
        ));
        pan_buku_table.setViewportView(tbl_buku);
        if (tbl_buku.getColumnModel().getColumnCount() > 0) {
            tbl_buku.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout pan_bukuLayout = new javax.swing.GroupLayout(pan_buku);
        pan_buku.setLayout(pan_bukuLayout);
        pan_bukuLayout.setHorizontalGroup(
            pan_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_bukuLayout.createSequentialGroup()
                .addGroup(pan_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_bukuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pan_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_author_buku)
                            .addComponent(btn_buku_buku))
                        .addGap(181, 181, 181)
                        .addComponent(btn_add_buku))
                    .addGroup(pan_bukuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pan_buku_table, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pan_bukuLayout.setVerticalGroup(
            pan_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_bukuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pan_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buku_buku)
                    .addComponent(btn_add_buku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_author_buku)
                .addGap(18, 18, 18)
                .addComponent(pan_buku_table, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pan_buku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pan_buku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buku_authMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buku_authMouseClicked
        // TODO add your handling code here:
        pan_buku.setVisible(true);
        pan_author.setVisible(false);
    }//GEN-LAST:event_btn_buku_authMouseClicked

    private void btn_author_authMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_author_authMouseClicked
        // TODO add your handling code here:
        pan_buku.setVisible(false);
        pan_author.setVisible(true);
    }//GEN-LAST:event_btn_author_authMouseClicked

    private void btn_add_authMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_authMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_authMouseClicked

    private void btn_author_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_author_bukuMouseClicked
        // TODO add your handling code here:
        pan_buku.setVisible(false);
        pan_author.setVisible(true);
    }//GEN-LAST:event_btn_author_bukuMouseClicked

    private void btn_buku_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buku_bukuMouseClicked
        // TODO add your handling code here:
        pan_buku.setVisible(true);
        pan_author.setVisible(false);
    }//GEN-LAST:event_btn_buku_bukuMouseClicked

    private void btn_add_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_bukuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_bukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_auth;
    private javax.swing.JButton btn_add_buku;
    private javax.swing.JButton btn_author_auth;
    private javax.swing.JButton btn_author_buku;
    private javax.swing.JButton btn_buku_auth;
    private javax.swing.JButton btn_buku_buku;
    private javax.swing.JPanel pan_author;
    private javax.swing.JScrollPane pan_author_table;
    private javax.swing.JPanel pan_buku;
    private javax.swing.JScrollPane pan_buku_table;
    private javax.swing.JTable tbl_author;
    private javax.swing.JTable tbl_buku;
    // End of variables declaration//GEN-END:variables
}
